version: '3.8'

x-db_common_config: &db_config
    image: ${DOCKER_REGISTRY_URL}/pgp16:latest
    networks:
      - onec_net
    restart: always
    expose:
      - ${PG_PORT}

services:
  srv:
    image: ${DOCKER_REGISTRY_URL}/onec-server:${ONEC_VERSION}
    container_name: onec-srv_${ONEC_VERSION}
    hostname: onec-docker
    restart: always
    volumes:
      - srv_data:${SRV_DATA}
      - srv_log:${SRV_LOG}
    environment:
      - TZ=${TZ}
      - INFOBASE_NAMES=${INFOBASE_NAMES}
      - GROUP_NAME=${GROUP_NAME}
    networks:
      - onec_net
    expose:
      - "1540-1541"
      - "1560-1591"
      - "1545"
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.srv.rule=Host(`onec.oooslk.ru`)"
      - "traefik.http.routers.srv.entrypoints=web"
      - "traefik.http.services.srv.loadbalancer.server.port=80"

  db_small:
    <<: *db_config
    container_name: onec-pgpro16-small
    environment:
      - PG_PASSWORD=${PG_PASSWORD}
    hostname: db_small
    volumes:
      - pg_data_small:${PGDATA}

  db_big:
    <<: *db_config
    container_name: onec-pgpro16-big
    environment:
      - INCLUDE_PGDEFAULT=yes
      - PG_PASSWORD=${PG_PASSWORD}
    hostname: db_big
    volumes:
      - pg_data_big:${PGDATA}

  pusk:
    image: segateekb/pusk:latest
    container_name: pusk
    hostname: pusk
    volumes:
      - pusk_data:${PUSK_DATA}
      - pusk_log:${PUSK_LOG}
    restart: always
    networks:
      - onec_net
    depends_on:
      - srv
    expose:
      - 8080
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pusk.rule=Host(`onec.oooslk.ru`)"
      - "traefik.http.routers.pusk.entrypoints=pusk"
      - "traefik.http.services.pusk.loadbalancer.server.port=8080"
      - "traefik.http.routers.pusk.middlewares=auth"


  traefik: 
    image: traefik:v2.5
    container_name: traefik
    environment:
    - PUSK_PASS=${PUSK_PASS}
    command:
    - "--api.insecure=true"
    - "--providers.docker=true"
    - "--providers.docker.exposedByDefault=false"
    - "--entrypoints.web.address=:80"
    - "--entrypoints.pusk.address=:8000"
    ports:
      - "80:80"
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - pusk
      - srv
    restart: always
    networks:
      - onec_net 
    labels:
    - "traefik.enable=true"
    - "traefik.http.middlewares.auth.basicauth.users=${PUSK_PASS}"

volumes:
  srv_data: {}
  srv_log: {}
  pusk_data: {}
  pusk_log: {}
  pg_data_small: {}
  pg_data_big: {}



networks:
  onec_net:
    driver: bridge
